const moviesFakeAPI = [
  {
    adult: false,
    backdrop_path: "/lNyLSOKMMeUPr1RsL4KcRuIXwHt.jpg",
    genre_ids: [878, 28],
    id: 580489,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    overview:
      "O relacionamento entre Eddie e Venom (Tom Hardy) está evoluindo. Buscando a melhor forma de lidar com a inevitável simbiose, esse dois lados descobrem como viver juntos e, de alguma forma, se tornarem melhores juntos do que separados.",
    popularity: 7933.523,
    poster_path: "/1BdFUd1FAgo0tLHejVQb5oeqevz.jpg",
    release_date: "2021-09-30",
    title: "Venom: Tempo de Carnificina",
    video: false,
    vote_average: 7,
    vote_count: 1106,
  },
  {
    adult: false,
    backdrop_path: "/Aebz7s8EHQXxHR98J8Vw6QVGggq.jpg",
    genre_ids: [28, 12, 18, 878],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Em um futuro distante, planetas são comandados por casas nobres que fazem parte de um império feudal intergalático. Paul Atreides é um jovem homem cuja família toma controle do planeta deserto Arrakis, também conhecido como Duna. A única fonte da especiaria melange, a substância mais importante do cosmos, Arrakis se prova ser um planeta nem um pouco fácil de governar.",
    popularity: 7628.716,
    poster_path: "/krrZTVEqrYwu6vR3f4NWgdSZg8X.jpg",
    release_date: "2021-09-15",
    title: "Duna",
    video: false,
    vote_average: 8.1,
    vote_count: 2392,
  },
  {
    adult: false,
    backdrop_path: "/2cdrhlf3hvvueGyQDx0u8jpWvQR.jpg",
    genre_ids: [27, 53],
    id: 610253,
    original_language: "en",
    original_title: "Halloween Kills",
    overview:
      "Minutos depois de Laurie Strode, sua filha Karen e sua neta Allyson deixarem o assassino mascarado Michael Myers enjaulado e queimando no porão de Laurie, Laurie é levada às pressas para o hospital com ferimentos graves, acreditando que ela finalmente matou seu torturador ao longo da vida. Mas quando Michael consegue se livrar da armadilha de Laurie, seu ritual de banho de sangue recomeça. Enquanto Laurie luta contra sua dor e se prepara para se defender dele, ela inspira todos em Haddonfield a se levantarem contra seu monstro imparável. As mulheres Strode se juntam a um grupo de outras sobreviventes da primeira violência de Michael, que decidem fazer justiça com as próprias mãos, formando uma multidão de vigilantes que começa a caçar Michael de uma vez por todas.",
    popularity: 4242.611,
    poster_path: "/4NphuHmnuROLqCjAEr5LS7Aage6.jpg",
    release_date: "2021-10-14",
    title: "Halloween Kills: O Terror Continua",
    video: false,
    vote_average: 7.3,
    vote_count: 687,
  },
  {
    adult: false,
    backdrop_path: "/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
    genre_ids: [35, 28, 12, 878],
    id: 550988,
    original_language: "en",
    original_title: "Free Guy",
    overview:
      "Um caixa de banco preso a uma entediante rotina tem sua vida virada de cabeça para baixo quando ele descobre que é personagem em um brutalmente realista vídeo game de mundo aberto. Agora ele precisa aceitar sua realidade e lidar com o fato de que é o único que pode salvar o mundo.",
    popularity: 3841.377,
    poster_path: "/jXlGeLOg2RKHmV9CinVaIB4ijKU.jpg",
    release_date: "2021-08-11",
    title: "Free Guy: Assumindo o Controle",
    video: false,
    vote_average: 7.8,
    vote_count: 3085,
  },
  {
    adult: false,
    backdrop_path: "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
    genre_ids: [878, 28],
    id: 335983,
    original_language: "en",
    original_title: "Venom",
    overview:
      "O jornalista Eddie Brock desenvolve força e poder sobre-humanos quando seu corpo se funde com o alienígena Venom. Dominado pela raiva, Venom tenta controlar as novas e perigosas habilidades de Eddie",
    popularity: 2479.153,
    poster_path: "/apZJb9kdHXhPu6oDTeztDSd41zw.jpg",
    release_date: "2018-09-28",
    title: "Venom",
    video: false,
    vote_average: 6.8,
    vote_count: 11944,
  },
  {
    adult: false,
    backdrop_path: "/kTOheVmqSBDIRGrQLv2SiSc89os.jpg",
    genre_ids: [16, 35, 10751],
    id: 639721,
    original_language: "en",
    original_title: "The Addams Family 2",
    overview:
      "Os Addams se envolvem em aventuras mais malucas e se envolvem em confrontos hilariantes com todos os tipos de personagens desavisados.",
    popularity: 2366.385,
    poster_path: "/ujWOI68vGkfLOgEDmcrjIS6il7B.jpg",
    release_date: "2021-10-01",
    title: "A Família Addams 2: Pé na Estrada",
    video: false,
    vote_average: 7.5,
    vote_count: 397,
  },
  {
    adult: false,
    backdrop_path: "/sjeEHzxdDrtMTHQwARi4UJ4NXN7.jpg",
    genre_ids: [878, 53, 9648],
    id: 675319,
    original_language: "en",
    original_title: "Zone 414",
    overview:
      "Zona 414 se passa em um futuro próximo em uma colônia de robôs humanóides de última geração. Quando a filha de seu criador desaparece, ele contrata o investigador particular David Carmichael para trazê-la para casa. David se junta a Jane, uma IA altamente avançada e autoconsciente, para rastrear a filha desaparecida.",
    popularity: 2216.371,
    poster_path: "/wIm5S6Blkb0qDMTGVu80VWSrQV1.jpg",
    release_date: "2021-09-03",
    title: "Zone 414",
    video: false,
    vote_average: 6,
    vote_count: 64,
  },
  {
    adult: false,
    backdrop_path: "/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg",
    genre_ids: [28, 12],
    id: 568620,
    original_language: "en",
    original_title: "Snake Eyes: G.I. Joe Origins",
    overview:
      "Após salvar a vida do herdeiro de Arashikage, Storm Shadow, Snake Eyes é aceito nesse antigo clã japonês se junta à batalha contra o grupo terrorista Cobra. Desafiando os limites, Snake Eyes será o melhor dos guerreiros ninjas. Porém, são revelados segredos do passado, testando sua honra e lealdade - mesmo que isso signifique perder tudo pelo que lutou.",
    popularity: 2158.182,
    poster_path: "/6IxMW3939dOCjzenwzkWEjgICVq.jpg",
    release_date: "2021-07-22",
    title: "G.I. Joe Origens: Snake Eyes",
    video: false,
    vote_average: 6.9,
    vote_count: 717,
  },
  {
    adult: false,
    backdrop_path: "/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg",
    genre_ids: [28, 35, 12],
    id: 772436,
    original_language: "es",
    original_title: "Matando Cabos 2: La Máscara del Máscara",
    overview:
      'Diante da morte inesperada de seu pai distante, El Máscara,  e do subsequente roubo de sua preciosa máscara, Rubén, Mascarita, se defrontará com seu passado. Junto com seu invencível guarda-costas Tony "O Canibal" e, um aliado inesperado, ele terá apenas um dia para recuperá-la e se reconciliar com a memória de seu pai.',
    popularity: 1806.683,
    poster_path: "/jxdKa1467pktAILLbfw6kZyQlbW.jpg",
    release_date: "2021-10-01",
    title: "Matando Cabos 2",
    video: false,
    vote_average: 8.2,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/owraiceOKtSOa3t8sp3wA9K2Ox6.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 703771,
    original_language: "en",
    original_title: "Deathstroke: Knights & Dragons - The Movie",
    overview:
      "Com sua alma despedaçada e seu filho preso, o mercenário e mestre assassino Slade Wilson terá que redimir os pecados do seu passado para alimentar as batalhas do seu futuro!",
    popularity: 1706.127,
    poster_path: "/ro7zs4rPRrhdlePR2TieNmm1Gxq.jpg",
    release_date: "2020-08-04",
    title: "Exterminador: Cavaleiros e Dragões",
    video: false,
    vote_average: 7,
    vote_count: 284,
  },
  {
    adult: false,
    backdrop_path: "/ux6gkGSKNFtp2NFYxwYFxVWdnGa.jpg",
    genre_ids: [80, 18, 53],
    id: 874948,
    original_language: "tr",
    original_title: "Kin",
    overview:
      "Um promotor público de sucesso se envolve em um mistério altamente arriscado.",
    popularity: 1693.01,
    poster_path: "/xSqtHT2DWbWBZ4dUvvMs6z1OfFK.jpg",
    release_date: "2021-10-08",
    title: "Dano Colateral",
    video: false,
    vote_average: 6.5,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: "/7h5WAPAcUzOWpp2jrwHBB48790j.jpg",
    genre_ids: [16, 28],
    id: 843241,
    original_language: "ja",
    original_title: "劇場版 七つの大罪 光に呪われし者たち",
    overview:
      "Meliodas e seus amigos entram em ação novamente quando a nova era de paz é ameaçada por uma poderosa aliança mágica que pode acabar com tudo.",
    popularity: 1514.316,
    poster_path: "/gtiNyP9BoQmPzjeDhvofUtUxpJV.jpg",
    release_date: "2021-07-02",
    title: "The Seven Deadly Sins: Cursed by Light",
    video: false,
    vote_average: 8.4,
    vote_count: 187,
  },
  {
    adult: false,
    backdrop_path: "/4KpNHvQIjyg1YFovRAoUXoFrGnR.jpg",
    genre_ids: [16, 12],
    id: 662708,
    original_language: "ja",
    original_title: "劇場版ポケットモンスター ココ",
    overview:
      "A história do novo filme se passa na Floresta Okoya, um paraíso Pokémon protegido por leis estritas que proíbem visitantes de pisar na área. O filme é centrado em Coco, um menino que foi criado por Pokémon e também se considera um, tratando o Pokémon Mítico Zarude como seu pai. Ash e Pikachu encontram Coco durante uma aventura.",
    popularity: 1512.493,
    poster_path: "/szrcgoMk7BJeSFJS41lMiyNPnf3.jpg",
    release_date: "2020-12-25",
    title: "Pokémon, o Filme: Segredos da Selva",
    video: false,
    vote_average: 7.6,
    vote_count: 54,
  },
  {
    adult: false,
    backdrop_path: "/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg",
    genre_ids: [14, 12, 35],
    id: 589754,
    original_language: "ru",
    original_title: "Последний богатырь: Корень зла",
    overview: "",
    popularity: 1475.778,
    poster_path: "/14l5EFPdqZ8Pzpp3yXO3BnTnpQh.jpg",
    release_date: "2021-01-01",
    title: "Последний богатырь: Корень зла",
    video: false,
    vote_average: 7.3,
    vote_count: 59,
  },
  {
    adult: false,
    backdrop_path: "/eBGKU0ZLJmxtVtzESTB1mfllX1J.jpg",
    genre_ids: [80, 28, 53],
    id: 630004,
    original_language: "en",
    original_title: "The Vault",
    overview:
      "Thom Laybrick é um jovem e brilhante engenheiro que dificilmente se atrai pelos projetos em que é chamado a participar. Mas ele diz sim quando o caçador de tesouros Walter o convida para se unir a um grupo de contraventores que pretendem realizar um assalto ao Banco da Espanha. Calculado em cada detalhe, o roubo se torna uma incessante luta contra o tempo para que consigam se dar bem em meio à Copa do Mundo em que a Espanha disputa a final.",
    popularity: 1436.674,
    poster_path: "/AhRSv4npEaE8ZvuJh4CmQpsXDZg.jpg",
    release_date: "2021-03-03",
    title: "Assalto ao Banco da Espanha",
    video: false,
    vote_average: 7.1,
    vote_count: 341,
  },
];

export default moviesFakeAPI;
